// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jMtExR8qwqZVcrohMcjTE5FmNeY7tpo',
    appId: '1:41501938250:web:88c880dfabc3d9ec894cb3',
    messagingSenderId: '41501938250',
    projectId: 'flower-app-fa7d9',
    authDomain: 'flower-app-fa7d9.firebaseapp.com',
    storageBucket: 'flower-app-fa7d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvW1ursyErV7xmgL3QN5emP_Zlg-W9v0',
    appId: '1:41501938250:android:41bce8fb3841dc15894cb3',
    messagingSenderId: '41501938250',
    projectId: 'flower-app-fa7d9',
    storageBucket: 'flower-app-fa7d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3sgEyne9lM9dr8NRcS7CJJiRfsA9gsU',
    appId: '1:41501938250:ios:329d62abe8d9c802894cb3',
    messagingSenderId: '41501938250',
    projectId: 'flower-app-fa7d9',
    storageBucket: 'flower-app-fa7d9.appspot.com',
    iosBundleId: 'com.example.flutterPlants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl3sgEyne9lM9dr8NRcS7CJJiRfsA9gsU',
    appId: '1:41501938250:ios:329d62abe8d9c802894cb3',
    messagingSenderId: '41501938250',
    projectId: 'flower-app-fa7d9',
    storageBucket: 'flower-app-fa7d9.appspot.com',
    iosBundleId: 'com.example.flutterPlants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jMtExR8qwqZVcrohMcjTE5FmNeY7tpo',
    appId: '1:41501938250:web:220a0fd69479bc57894cb3',
    messagingSenderId: '41501938250',
    projectId: 'flower-app-fa7d9',
    authDomain: 'flower-app-fa7d9.firebaseapp.com',
    storageBucket: 'flower-app-fa7d9.appspot.com',
  );

}